# Use the same Rust base image
FROM rust:1.70 as development
WORKDIR /usr/src
USER root

# Install development tools (like cargo-watch)
RUN cargo install cargo-watch
RUN cargo install cargo-make

# Install Bun and global packages as before
RUN curl -fsSL https://bun.sh/install | bash && \
  ln -s $HOME/.bun/bin/bun /usr/local/bin/bun
RUN bun install -g tailwindcss

# Copy only what is necessary for dependency resolution
COPY nebula_lib/Cargo.toml nebula_lib/Cargo.lock ./nebula_lib/
COPY web_server/Cargo.toml web_server/Cargo.lock ./web_server/
COPY web_server/Makefile.toml web_server/Makefile.toml ./web_server/

# # Dummy build for nebula_lib
# RUN mkdir -p nebula_lib/src && echo "fn main() {}" > nebula_lib/src/lib.rs && cargo build --manifest-path nebula_lib/Cargo.toml
# # # Dummy build for web_server
# RUN mkdir -p web_server/src && echo "fn main() {}" > web_server/src/main.rs && cargo build --manifest-path web_server/Cargo.toml


# Mount the source code as a volume
VOLUME ["/usr/src/nebula_lib/src", "/usr/src/web_server/src", "/usr/src/web_server/styles", "/usr/src/web_server/templates", "/usr/src/web_server/assets"]

# Expose the port the application runs on
EXPOSE 8000

#WORKDIR ./web_server

# Set the command to run your application using cargo-watch for live reloading
CMD ["sh", "-c", "cd ./web_server && cargo make run-dev"]
