[package]
name = "mc_estimate_pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
shared = { path = "../shared" }

[features]
docker = []
