[tasks.run-dev]
script_runner = "bash"
script = ['''
trap "exit" INT TERM ERR
trap "kill 0" EXIT

cargo run --target aarch64-apple-darwin &
pnpm dlx tailwindcss -i styles/tailwind.css -o assets/main.css --watch &

wait
''']
