[tasks.run-dev]
script_runner = "bash"
script = ['''
trap "exit" INT TERM ERR
trap "kill 0" EXIT

cargo watch -x "run --target aarch64-apple-darwin" &
bun x tailwindcss -i styles/tailwind.css -o assets/main.css --watch

wait
''']
# pnpm dlx tailwindcss -i styles/tailwind.css -o assets/main.css --watch
# cargo watch -x "run --target aarch64-apple-darwin" &

[tasks.run-docker-dev]
script_runner = "bash"
script = ['''
trap "exit" INT TERM ERR
trap "kill 0" EXIT

cargo watch -x "run -- -p 1234 -a 0.0.0.0" &
bun x tailwindcss -i styles/tailwind.css -o assets/main.css --watch

wait
''']
# pnpm dlx tailwindcss -i styles/tailwind.css -o assets/main.css --watch
# cargo watch -x "run --target aarch64-apple-darwin" &
