name: Please scp

on:
  push:
    branches: [scp]

jobs:
  build:
    name: "Test nebula on ${{matrix.os}}"
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Prepare deploy
        run: echo "marco" > marco.txt

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          # password: ${{ secrets.SERVER_PASSWORD }} # Use either password or key
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "marco.txt"
          target: "/home/debian/"

      - name: Cleanup
        run: rm marco.txt
